# mgw fish completion script
# Place in ~/.config/fish/completions/mgw.fish
# or run: fisher install (if using a fish plugin manager)
# Generated by bin/generate-completions.cjs

# Disable file completions by default for mgw
complete -c mgw -f

# ---------------------------------------------------------------------------
# Global flags (available for all subcommands)
# ---------------------------------------------------------------------------
complete -c mgw -n '__fish_use_subcommand' -l dry-run  -d 'show what would happen without executing'
complete -c mgw -n '__fish_use_subcommand' -l json     -d 'output structured JSON'
complete -c mgw -n '__fish_use_subcommand' -s v -l verbose -d 'show API calls and file writes'
complete -c mgw -n '__fish_use_subcommand' -l debug    -d 'full payloads and timings'
complete -c mgw -n '__fish_use_subcommand' -l model    -d 'Claude model override' -r

# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------
complete -c mgw -n '__fish_use_subcommand' -a run       -d 'Run the full pipeline for an issue'
complete -c mgw -n '__fish_use_subcommand' -a init      -d 'Bootstrap repo for MGW (state, templates, labels)'
complete -c mgw -n '__fish_use_subcommand' -a project   -d 'Initialize project from template (milestones, issues, ROADMAP)'
complete -c mgw -n '__fish_use_subcommand' -a milestone -d 'Execute milestone issues in dependency order'
complete -c mgw -n '__fish_use_subcommand' -a next      -d 'Show next unblocked issue'
complete -c mgw -n '__fish_use_subcommand' -a issue     -d 'Triage issue against codebase'
complete -c mgw -n '__fish_use_subcommand' -a update    -d 'Post status comment on issue'
complete -c mgw -n '__fish_use_subcommand' -a pr        -d 'Create PR from GSD artifacts'
complete -c mgw -n '__fish_use_subcommand' -a sync      -d 'Reconcile .mgw/ state with GitHub'
complete -c mgw -n '__fish_use_subcommand' -a issues    -d 'Browse open issues'
complete -c mgw -n '__fish_use_subcommand' -a link      -d 'Cross-reference issues/PRs/branches'
complete -c mgw -n '__fish_use_subcommand' -a help      -d 'Show command reference'

# ---------------------------------------------------------------------------
# run <issue-number>
# ---------------------------------------------------------------------------
complete -c mgw -n '__fish_seen_subcommand_from run' -l quiet -d 'buffer output, show summary at end'
complete -c mgw -n '__fish_seen_subcommand_from run' -l auto  -d 'phase chaining: discuss -> plan -> execute'
complete -c mgw -n '__fish_seen_subcommand_from run' -l dry-run -d 'show what would happen without executing'
complete -c mgw -n '__fish_seen_subcommand_from run' -l json    -d 'output structured JSON'
complete -c mgw -n '__fish_seen_subcommand_from run' -s v -l verbose -d 'show API calls and file writes'
complete -c mgw -n '__fish_seen_subcommand_from run' -l debug   -d 'full payloads and timings'
complete -c mgw -n '__fish_seen_subcommand_from run' -l model   -d 'Claude model override' -r

# ---------------------------------------------------------------------------
# milestone [number]
# ---------------------------------------------------------------------------
complete -c mgw -n '__fish_seen_subcommand_from milestone' -l interactive -d 'pause between issues for review'
complete -c mgw -n '__fish_seen_subcommand_from milestone' -l dry-run -d 'show what would happen without executing'
complete -c mgw -n '__fish_seen_subcommand_from milestone' -l json    -d 'output structured JSON'
complete -c mgw -n '__fish_seen_subcommand_from milestone' -s v -l verbose -d 'show API calls and file writes'
complete -c mgw -n '__fish_seen_subcommand_from milestone' -l debug   -d 'full payloads and timings'
complete -c mgw -n '__fish_seen_subcommand_from milestone' -l model   -d 'Claude model override' -r

# ---------------------------------------------------------------------------
# pr [number]
# ---------------------------------------------------------------------------
complete -c mgw -n '__fish_seen_subcommand_from pr' -l base  -d 'custom base branch' -r
complete -c mgw -n '__fish_seen_subcommand_from pr' -l dry-run -d 'show what would happen without executing'
complete -c mgw -n '__fish_seen_subcommand_from pr' -l json    -d 'output structured JSON'
complete -c mgw -n '__fish_seen_subcommand_from pr' -s v -l verbose -d 'show API calls and file writes'
complete -c mgw -n '__fish_seen_subcommand_from pr' -l debug   -d 'full payloads and timings'
complete -c mgw -n '__fish_seen_subcommand_from pr' -l model   -d 'Claude model override' -r

# ---------------------------------------------------------------------------
# issues [filters]
# ---------------------------------------------------------------------------
complete -c mgw -n '__fish_seen_subcommand_from issues' -l label     -d 'filter by label' -r
complete -c mgw -n '__fish_seen_subcommand_from issues' -l milestone -d 'filter by milestone' -r
complete -c mgw -n '__fish_seen_subcommand_from issues' -l assignee  -d 'filter by assignee' -r -a 'all @me'
complete -c mgw -n '__fish_seen_subcommand_from issues' -l state     -d 'issue state' -r -a 'open closed all'
complete -c mgw -n '__fish_seen_subcommand_from issues' -s s -l search -d 'pre-populate fuzzy search input' -r
complete -c mgw -n '__fish_seen_subcommand_from issues' -l limit     -d 'max issues to load' -r -a '10 25 50 100'
complete -c mgw -n '__fish_seen_subcommand_from issues' -l dry-run   -d 'show what would happen without executing'
complete -c mgw -n '__fish_seen_subcommand_from issues' -l json      -d 'output structured JSON'
complete -c mgw -n '__fish_seen_subcommand_from issues' -s v -l verbose -d 'show API calls and file writes'
complete -c mgw -n '__fish_seen_subcommand_from issues' -l debug     -d 'full payloads and timings'
complete -c mgw -n '__fish_seen_subcommand_from issues' -l model     -d 'Claude model override' -r

# ---------------------------------------------------------------------------
# link <ref-a> <ref-b>
# ---------------------------------------------------------------------------
complete -c mgw -n '__fish_seen_subcommand_from link' -l quiet   -d 'no GitHub comments'
complete -c mgw -n '__fish_seen_subcommand_from link' -l dry-run -d 'show what would happen without executing'
complete -c mgw -n '__fish_seen_subcommand_from link' -l json    -d 'output structured JSON'
complete -c mgw -n '__fish_seen_subcommand_from link' -s v -l verbose -d 'show API calls and file writes'
complete -c mgw -n '__fish_seen_subcommand_from link' -l debug   -d 'full payloads and timings'
complete -c mgw -n '__fish_seen_subcommand_from link' -l model   -d 'Claude model override' -r

# ---------------------------------------------------------------------------
# Subcommands that only take global flags (no subcommand-specific flags)
# ---------------------------------------------------------------------------
for _mgw_cmd in init project next issue update sync help
  complete -c mgw -n "__fish_seen_subcommand_from $_mgw_cmd" -l dry-run -d 'show what would happen without executing'
  complete -c mgw -n "__fish_seen_subcommand_from $_mgw_cmd" -l json    -d 'output structured JSON'
  complete -c mgw -n "__fish_seen_subcommand_from $_mgw_cmd" -s v -l verbose -d 'show API calls and file writes'
  complete -c mgw -n "__fish_seen_subcommand_from $_mgw_cmd" -l debug   -d 'full payloads and timings'
  complete -c mgw -n "__fish_seen_subcommand_from $_mgw_cmd" -l model   -d 'Claude model override' -r
end
