#!/usr/bin/env bash
# mgw bash completion script
# Source this file or add to /etc/bash_completion.d/mgw
# Generated by bin/generate-completions.cjs

_mgw() {
  local cur prev words cword
  _init_completion || return

  local subcommands="run init project milestone next issue update pr sync issues link help"

  local global_flags="--dry-run --json --verbose -v --debug --model"

  case "$prev" in
    mgw)
      COMPREPLY=( $(compgen -W "$subcommands $global_flags" -- "$cur") )
      return
      ;;
    run)
      COMPREPLY=( $(compgen -W "--quiet --auto $global_flags" -- "$cur") )
      return
      ;;
    init)
      COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )
      return
      ;;
    project)
      COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )
      return
      ;;
    milestone)
      COMPREPLY=( $(compgen -W "--interactive $global_flags" -- "$cur") )
      return
      ;;
    next)
      COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )
      return
      ;;
    issue)
      COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )
      return
      ;;
    update)
      COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )
      return
      ;;
    pr)
      COMPREPLY=( $(compgen -W "--base $global_flags" -- "$cur") )
      return
      ;;
    sync)
      COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )
      return
      ;;
    issues)
      COMPREPLY=( $(compgen -W "--label --milestone --assignee --state --search -s --limit $global_flags" -- "$cur") )
      return
      ;;
    link)
      COMPREPLY=( $(compgen -W "--quiet $global_flags" -- "$cur") )
      return
      ;;
    help)
      COMPREPLY=()
      return
      ;;
    --model)
      # Offer common Claude model names
      COMPREPLY=( $(compgen -W "claude-opus-4-5 claude-sonnet-4-5 claude-haiku-4-5" -- "$cur") )
      return
      ;;
    --state)
      COMPREPLY=( $(compgen -W "open closed all" -- "$cur") )
      return
      ;;
    --assignee)
      COMPREPLY=( $(compgen -W "all @me" -- "$cur") )
      return
      ;;
  esac

  # If cur starts with - complete flags for the current subcommand
  if [[ "$cur" == -* ]]; then
    # Find the subcommand in words
    local subcmd=""
    for word in "${words[@]}"; do
      if [[ " $subcommands " == *" $word "* ]]; then
        subcmd="$word"
        break
      fi
    done

    case "$subcmd" in
      run)      COMPREPLY=( $(compgen -W "--quiet --auto $global_flags" -- "$cur") ) ;;
      milestone) COMPREPLY=( $(compgen -W "--interactive $global_flags" -- "$cur") ) ;;
      pr)       COMPREPLY=( $(compgen -W "--base $global_flags" -- "$cur") ) ;;
      issues)   COMPREPLY=( $(compgen -W "--label --milestone --assignee --state --search -s --limit $global_flags" -- "$cur") ) ;;
      link)     COMPREPLY=( $(compgen -W "--quiet $global_flags" -- "$cur") ) ;;
      *)        COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") ) ;;
    esac
    return
  fi

  # Default: suggest subcommands
  COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )
}

complete -F _mgw mgw
