#compdef mgw
# mgw zsh completion script
# Place in a directory on your $fpath (e.g. /usr/local/share/zsh/site-functions/_mgw)
# or source directly: source completions/mgw.zsh
# Generated by bin/generate-completions.cjs

_mgw() {
  local context state state_descr line
  typeset -A opt_args

  local -a global_flags
  global_flags=(
    '--dry-run[show what would happen without executing]'
    '--json[output structured JSON]'
    '(-v --verbose)'{-v,--verbose}'[show API calls and file writes]'
    '--debug[full payloads and timings]'
    '--model[Claude model override]:model:(claude-opus-4-5 claude-sonnet-4-5 claude-haiku-4-5)'
  )

  _arguments -C \
    "${global_flags[@]}" \
    '(-h --help)'{-h,--help}'[display help]' \
    '(-V --version)'{-V,--version}'[output the version number]' \
    '1: :_mgw_subcommands' \
    '*:: :->subcommand_args' \
    && return 0

  case "$state" in
    subcommand_args)
      case "$words[1]" in
        run)
          _arguments \
            "${global_flags[@]}" \
            '--quiet[buffer output, show summary at end]' \
            '--auto[phase chaining: discuss -> plan -> execute]' \
            '1:issue-number:_mgw_issue_numbers' \
            && return 0
          ;;
        init)
          _arguments "${global_flags[@]}" && return 0
          ;;
        project)
          _arguments "${global_flags[@]}" && return 0
          ;;
        milestone)
          _arguments \
            "${global_flags[@]}" \
            '--interactive[pause between issues for review]' \
            '1::milestone-number:' \
            && return 0
          ;;
        next)
          _arguments "${global_flags[@]}" && return 0
          ;;
        issue)
          _arguments \
            "${global_flags[@]}" \
            '1:issue-number:_mgw_issue_numbers' \
            && return 0
          ;;
        update)
          _arguments \
            "${global_flags[@]}" \
            '1:issue-number:_mgw_issue_numbers' \
            '2::message:' \
            && return 0
          ;;
        pr)
          _arguments \
            "${global_flags[@]}" \
            '--base[custom base branch]:branch:_git_branch_names' \
            '1::issue-number:_mgw_issue_numbers' \
            && return 0
          ;;
        sync)
          _arguments "${global_flags[@]}" && return 0
          ;;
        issues)
          _arguments \
            "${global_flags[@]}" \
            '--label[filter by label]:label:' \
            '--milestone[filter by milestone]:milestone:' \
            '--assignee[filter by assignee]:assignee:(all @me)' \
            '--state[issue state]:state:(open closed all)' \
            '(-s --search)'{-s,--search}'[pre-populate fuzzy search input]:query:' \
            '--limit[max issues to load]:number:(10 25 50 100)' \
            && return 0
          ;;
        link)
          _arguments \
            "${global_flags[@]}" \
            '--quiet[no GitHub comments]' \
            '1:ref-a:' \
            '2:ref-b:' \
            && return 0
          ;;
        help)
          return 0
          ;;
      esac
      ;;
  esac
}

_mgw_subcommands() {
  local -a subcommands
  subcommands=(
    'run:Run the full pipeline for an issue'
    'init:Bootstrap repo for MGW (state, templates, labels)'
    'project:Initialize project from template (milestones, issues, ROADMAP)'
    'milestone:Execute milestone issues in dependency order'
    'next:Show next unblocked issue'
    'issue:Triage issue against codebase'
    'update:Post status comment on issue'
    'pr:Create PR from GSD artifacts'
    'sync:Reconcile .mgw/ state with GitHub'
    'issues:Browse open issues'
    'link:Cross-reference issues/PRs/branches'
    'help:Show command reference'
  )
  _describe 'mgw subcommand' subcommands
}

_mgw_issue_numbers() {
  # Attempt to complete issue numbers from active .mgw/ state
  local -a active_issues
  local active_dir=".mgw/active"
  if [[ -d "$active_dir" ]]; then
    for f in "$active_dir"/*.json; do
      [[ -f "$f" ]] || continue
      local num="${${f:t}%%[-_]*}"
      [[ "$num" =~ ^[0-9]+$ ]] && active_issues+=("$num")
    done
  fi
  if (( ${#active_issues[@]} > 0 )); then
    _describe 'issue number' active_issues
  else
    _message 'issue number'
  fi
}

_mgw "$@"
